apiVersion: apps/v1
kind: Deployment
metadata:
  name: cookmate-fe
  namespace: cookmate
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: cookmate-fe
  template:
    metadata:
      labels:
        app: cookmate-fe
    spec:
      containers:
      - name: cookmate-fe
        image: kiennlt/cookmate-fe:v5
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env: []
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
      # No imagePullSecrets required for public DockerHub images

---
apiVersion: v1
kind: Service
metadata:
  name: cookmate-fe
  namespace: cookmate
spec:
  selector:
    app: cookmate-fe
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
