apiVersion: apps/v1
kind: Deployment
metadata:
  name: cookmate-user
  namespace: cookmate
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%  
  selector:
    matchLabels:
      app: cookmate-user
  template:
    metadata:
      labels:
        app: cookmate-user
    spec:
      containers:
      - name: cookmate-user
        image: kiennlt/cookmate-user:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: cookmate-user
  namespace: cookmate
spec:
  selector:
    app: cookmate-user
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
